import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { Check } from "../assets/svgs/Check";
import { Facebook } from "../assets/svgs/Facebook";
import { Instagram } from "../assets/svgs/Instagram";
import { Link } from "../assets/svgs/Link";
import { Linkedin } from "../assets/svgs/Linkedin";
import { Logo } from "../assets/svgs/Logo";
import { LogoText } from "../assets/svgs/LogoText";
import { Fb } from "../assets/svgs/Fb";
import { Twi } from "../assets/svgs/Twi";
import { In } from "../assets/svgs/In";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [focus, setFocus] = useState(false);
  const texts = [
    "Check product availibility",
    "Get notified easily",
    "Subscribe multipe stores",
    "Browse 100+ stores",
  ];
  const SocialMedias = [
    {
      text: "Instagram",
      icon: <Instagram />,
      link: "https://www.instagram.com/offingoofficial/",
    },
    {
      text: "Facebook",
      icon: <Facebook />,
      link: "https://www.facebook.com/offingoofficial/?_rdr",
    },
    {
      text: "Linkedin",
      icon: <Linkedin />,
      link: "https://www.linkedin.com/in/offingoofficial/?originalSubdomain=in",
    },
  ];
  const clothes = [
    styles.cloth1,
    styles.cloth2,
    styles.cloth3,
    styles.cloth4,
    styles.cloth5,
    styles.cloth6,
  ];
  const blogs = [
    {
      title: "Heading goes here",
      content:
        "Donec sed erat ut magna suscipit mattis. Aliquam erat vaolutpat. Morbi in orci risus. Donec pretium fringilla blandit. Etiam ut....",
      date: "September 9, 2013",
    },
    {
      title: "Heading goes here",
      content:
        "Donec sed erat ut magna suscipit mattis. Aliquam erat vaolutpat. Morbi in orci risus. Donec pretium fringilla blandit. Etiam ut....",
      date: "September 9, 2013",
    },
    {
      title: "Heading goes here",
      content:
        "Donec sed erat ut magna suscipit mattis. Aliquam erat vaolutpat. Morbi in orci risus. Donec pretium fringilla blandit. Etiam ut....",
      date: "September 9, 2013",
    },
    {
      title: "Heading goes here",
      content:
        "Donec sed erat ut magna suscipit mattis. Aliquam erat vaolutpat. Morbi in orci risus. Donec pretium fringilla blandit. Etiam ut....",
      date: "September 9, 2013",
    },
    {
      title: "Heading goes here",
      content:
        "Donec sed erat ut magna suscipit mattis. Aliquam erat vaolutpat. Morbi in orci risus. Donec pretium fringilla blandit. Etiam ut....",
      date: "September 9, 2013",
    },
    {
      title: "Heading goes here",
      content:
        "Donec sed erat ut magna suscipit mattis. Aliquam erat vaolutpat. Morbi in orci risus. Donec pretium fringilla blandit. Etiam ut....",
      date: "September 9, 2013",
    },
  ];
  const Footer = [
    {
      category: "company",
      contents: [
        "Who We Are",
        "Blog",
        "Careers",
        "Report Fraud",
        "Contact",
        "Investor Relations",
      ],
    },
    {
      category: "For you",
      contents: ["Privacy", "Terms", "Security", "Sitemap"],
    },
  ];
  const FooterMedia = [
    {
      icon: <Fb />,
      link: "https://www.facebook.com/offingoofficial/?_rdr",
    },
    {
      icon: <Twi />,
      link: "https://mobile.twitter.com/offingoofficial",
    },
    {
      icon: <In />,
      link: "https://www.linkedin.com/in/offingoofficial/?originalSubdomain=in",
    },
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Offingo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <div className={styles.webLogo}>
          <Logo />
          <LogoText />
        </div>
        <div className={styles.mid}>
          <div className={styles.left}>
            <h1 className={styles.heading}>We&apos;re launching sooon!!!</h1>
            <p
              style={{ color: "#A0AEC0", fontSize: "20px", marginTop: "-30px" }}
            >
              Notify me when it lauches
            </p>
            <div
            className={styles.InputDiv}
              style={{
                border: focus ? "1px solid #3182CE" : "1px solid #E2E8F0",
              }}
            >
              <input
                style={{
                  flexGrow: 1,
                  backgroundColor: "transparent",
                  border: "transparent",
                  padding: "17px 0 17px 15px",
                  outline: "none",
                  fontSize: "16px",
                  width: "100%",
                }}
                onFocus={() => setFocus(true)}
                onBlur={() => setFocus(false)}
                type="text"
                placeholder="Enter your mobile number"
              />
              <button className={styles.phoneButton}>Notify me</button>
            </div>
            <div>
              <p
                style={{
                  color: "#A0AEC0",
                  fontSize: "20px",
                  marginTop: "84px",
                }}
              >
                Connect with us on
              </p>
              <div className={styles.social_medias}>
                {SocialMedias.map((element, index) => (
                  <a
                    key={index}
                    rel="noreferrer"
                    target="_blank"
                    href={element.link}
                  >
                    <div className={styles.social_button}>
                      {element.icon}
                      {element.text}
                      <Link />
                    </div>
                  </a>
                ))}
              </div>
            </div>
          </div>

          <div className={styles.clothes}>
            {clothes.map((element, index) => (
              <div key={element} className={`${styles.dress} ${element}`}>
                <Image layout="fill" src={`/cloth${index + 1}.png`} alt="" />
              </div>
            ))}
          </div>

          <div
            style={{
              marginLeft: "auto",
              width: "100%",
              display: "flex",
              height: "inherit",
              justifyContent: "end",
              alignItems: "end",
            }}
          >
            <div className={styles.logoImage}>
              <div className={styles.rightTexts}>
                {texts.map((element, index) => (
                  <div
                    key={index}
                    className={styles.texts}
                    style={{
                      borderBottom: index !== 3 ? "2px solid #F56565" : "",
                    }}
                  >
                    <Check /> {element}
                  </div>
                ))}
                <p >
                  & many more...
                </p>
              </div>
              <div className={styles.logoBox}></div>
              <Image layout="fill" src="/image.png" alt="" />
            </div>
          </div>
        </div>
        <div className={styles.blog}>
          <p
            style={{
              fontWeight: 500,
              fontSize: "30px",
              color: "#111213",
              marginLeft: "8%",
            }}
          >
            Blogs
          </p>
          <div className={styles.blogMain}>
            {blogs.map((element, index) => (
              <div key={index} className={styles.blogDiv}>
                <div className={styles.blogImage}></div>
                <div className={styles.blogContent}>
                  <h3>{element.title}</h3>
                  <h4>{element.content}</h4>
                  <p>{element.date}</p>
                  <a href="">READ MORE...</a>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <div style={{ flexGrow: 1 }}>
          <Logo />
          <p
            style={{
              fontStyle: "normal",
              fontWeight: 500,
              fontSize: "16px",
              lineHeight: "30px",
              color: "#838DA6",
            }}
          >
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam
            dolores quidem mollitia id ipsa nisi necessitatibus iure repudiandae
            aperiam, odit ipsam dolor fugiat corporis nesciunt illo nemo minus.
          </p>
        </div>
        <div className={styles.footer2}>
          {Footer.map((element, index) => (
            <div key={index}>
              <h2 style={{ whiteSpace: "nowrap", color: "white" }}>
                {element.category}
              </h2>
              {element.contents.map((ele, i) => (
                <p style={{ color: "#838DA6" }} key={i}>
                  {ele}
                </p>
              ))}
            </div>
          ))}
          <div>
            <h2 style={{ color: "white" }}>Social Link</h2>
            <div className={styles.footerMainMedia}>
              {FooterMedia.map((element, index) => (
                <a
                  key={index}
                  rel="noreferrer"
                  target="_blank"
                  href={element.link}
                >
                  <div className={styles.footerMedia}>{element.icon}</div>
                </a>
              ))}
            </div>
            <p style={{ color: "#838DA6" }}>Download app from </p>
            <div className={styles.footerImg}>
              <Image width="135.5px" height="39.71px" src={"/app.png"} alt="" />
              <Image
                width="135.5px"
                height="39.71px"
                src={"/play.png"}
                alt=""
              />
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
