import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { Check } from "../assets/svgs/Check";
import { Link } from "../assets/svgs/Link";
import { Logo } from "../assets/svgs/Logo";
import { LogoText } from "../assets/svgs/LogoText";
import styles from "../styles/Home.module.css";
import { useDispatch } from "react-redux";
import { getBlogData } from "../redux/actions/main";
import FooterCom from "../components/FooterCom";
import { texts, SocialMedias, clothes } from "../components/data";
import Blogs from "../components/Blogs";
import { ChakraProvider, Text } from "@chakra-ui/react";

export default function Home() {
  const dispatch = useDispatch();
  const [focus, setFocus] = useState(false);
  useEffect(() => {
    dispatch(getBlogData());
  }, [dispatch]);
  return (
    <ChakraProvider>
      <div className={styles.container}>
        <Head>
          <title>Offingo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>

        <main className={styles.main}>
          <div className={styles.webLogo}>
            <div style={{ width: "139px" }}>
              <Logo />
            </div>
            <p style={{fontSize:'14px', fontWeight:500, textAlign:"center", fontStyle:'italic', color: "#838DA6"}} >Making your <q style={{color:'red'}}>Clothing shopping experience</q> better</p>
          </div>
          <div className={styles.mid}>
            <div className={styles.left}>
              <h1 className={styles.heading}>We&apos;re launching sooon!!!</h1>
              <p
                style={{
                  color: "#A0AEC0",
                  fontSize: "20px",
                }}
              >
                Notify me when it lauches
              </p>
              <div
                className={styles.InputDiv}
                style={{
                  border: focus ? "1px solid #3182CE" : "1px solid #E2E8F0",
                }}
              >
                <input
                  style={{
                    flexGrow: 1,
                    backgroundColor: "transparent",
                    border: "transparent",
                    padding: "17px 0 17px 15px",
                    outline: "none",
                    fontSize: "16px",
                    width: "100%",
                  }}
                  onFocus={() => setFocus(true)}
                  onBlur={() => setFocus(false)}
                  type="text"
                  placeholder="Enter your mobile number"
                />
                <button className={styles.phoneButton}>Notify me</button>
              </div>
              <div>
                <p
                  className={styles.soacialP}
                  style={{
                    color: "#A0AEC0",
                    fontSize: "20px",
                    margin: "84px 0 20px",
                  }}
                >
                  Connect with us on
                </p>
                <div className={styles.social_medias}>
                  {SocialMedias.map((element, index) => (
                    <a
                      key={index}
                      rel="noreferrer"
                      target="_blank"
                      href={element.link}
                    >
                      <div className={styles.social_button}>
                        {element.icon}
                        {element.text}
                        <Link />
                      </div>
                    </a>
                  ))}
                </div>
              </div>
            </div>

            <div className={styles.clothes}>
              {clothes.map((element, index) => (
                <div key={element} className={`${styles.dress} ${element}`}>
                  <Image layout="fill" src={`/cloth${index + 1}.png`} alt="" />
                </div>
              ))}
            </div>

            <div className={styles.right}>
              <div className={styles.rightBox}>
                <div className={styles.logoImage}>
                  <div className={styles.rightTexts}>
                    {texts.map((element, index) => (
                      <div
                        key={index}
                        className={styles.texts}
                        style={{
                          borderBottom: index !== 3 ? "2px solid #F56565" : "",
                        }}
                      >
                        <Check /> {element}
                      </div>
                    ))}
                    <p>& many more...</p>
                  </div>
                  <div className={styles.logoBox}></div>
                  <Image layout="fill" src="/image.png" alt="" />
                </div>
              </div>
            </div>
          </div>
          <div className={styles.blog}>
            <Text fontSize={30} fontWeight={500} color="#111213" ml="8%">
              {" "}
              Blogs
            </Text>
            <Blogs />
          </div>
        </main>

        <footer className={styles.footer}>
          <FooterCom />
        </footer>
      </div>
    </ChakraProvider>
  );
}
